### ISSUE TITLE
Update Public Header Documentation to Doxygen Style

### ISSUE THREAD

**Issue by scoopxyz** [AcademySoftwareFoundation/OpenColorIO#1059]

**Comment by doug-walker** [comment]
We discussed this at the 2020-11-13 documentation working group meeting.  The first deliverable for this issue should be to take one of the public headers (or even a section of it), put it into Doxygen style, and present the output (as it would appear in the documentation) for review by the community.

One issue to be decided is how verbose to make it.  The original OCIO headers had a very succinct style where many arguments, functions, and methods whose meaning was obvious were not documented.  Do we want to continue with this style or make it more verbose?

**Comment by michdolan** [comment]
I think if a function is clearly named and has detailed type info it can remain succinct. If however there is any ambiguity about what a class or function does, or how it is intended to be used, we should document it with adequate verbosity to understand it without having to reach out to the community for explanation. Not that there's anything wrong with asking for help/clarification in the community, but it would be good to strive for understanding in isolation if possible.

**Comment by zachlewis** [comment]
I volunteered at that 2020-11-13 documentation working group meeting to take a stab at this... and I've been procrastinating ever since :)

I have zero experience with doxygen, but I'm definitely willing to put the work in. Barring no objections, I'll try to have at least part of one of the headers converted and rendered for the next time we meet.

**Comment by doug-walker** [comment]
Excellent, thanks Zach!
