### ISSUE TITLE
PyOpenColorIO: Config.GetProcessor() vs Config.getProcessor()

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1122]
It seems there's an overloaded "GetProcessor" method, which is responsible for constructing processors with respect to separate source and destination configs; and then there's a separate "getProcessor" overloaded method for constructing processors with a single config.

This is pretty confusing. What would you guys say to either renaming one of the methods, or combining them into a single overloaded method?

**Comment by doug-walker** [comment]
@zachlewis , could you make a more specific proposal?  It's not clear to us whether your problem is with the "G" vs "g" or you think another name is needed.  The case difference is simply due to following the existing coding style for functions vs. methods.  The naming is consistent with the current getProcessor usage since there are already a wide range of different signatures that are used for various different ways of building a processor, so that's why we didn't use GetProcessorFromConfigs or something like that.

**Comment by zachlewis** [comment]
Ah, I'm sorry, I wasn't being clear.

I don't have an issue with style -- my issue is that, _presently_ in the Python API, we have both:
PyOpenColorIO.Config.getProcessor(...) 
PyOpenColorIO.Config.GetProcessor(...)

They have different type signatures, but serve complementary functions:

`PyOpenColorIO.Config.getProcessor(...)
    getProcessor(*args, **kwargs)
    Overloaded function.
    
    1. getProcessor(self: PyOpenColorIO.Config, srcColorSpace: OpenColorIO_v2_0dev::ColorSpace, dstColorSpace: OpenColorIO_v2_0dev::ColorSpace) -> OpenColorIO_v2_0dev::Processor
    
    2. getProcessor(self: PyOpenColorIO.Config, context: OpenColorIO_v2_0dev::Context, srcColorSpace: OpenColorIO_v2_0dev::ColorSpace, dstColorSpace: OpenColorIO_v2_0dev::ColorSpace) -> OpenColorIO_v2_0dev::Processor
    
    3. getProcessor(self: PyOpenColorIO.Config, srcColorSpaceName: str, dstColorSpaceName: str) -> OpenColorIO_v2_0dev::Processor
    
    4. getProcessor(self: PyOpenColorIO.Config, context: OpenColorIO_v2_0dev::Context, srcColorSpaceName: str, dstColorSpaceName: str) -> OpenColorIO_v2_0dev::Processor
    
    5. getProcessor(self: PyOpenColorIO.Config, srcColorSpaceName: str, display: str, view: str) -> OpenColorIO_v2_0dev::Processor
    
    6. getProcessor(self: PyOpenColorIO.Config, context: OpenColorIO_v2_0dev::Context, srcColorSpaceName: str, display: str, view: str) -> OpenColorIO_v2_0dev::Processor
    
    7. getProcessor(self: PyOpenColorIO.Config, transform: PyOpenColorIO.Transform) -> OpenColorIO_v2_0dev::Processor
    
    8. getProcessor(self: PyOpenColorIO.Config, transform: PyOpenColorIO.Transform, direction: PyOpenColorIO.TransformDirection) -> OpenColorIO_v2_0dev::Processor
    
    9. getProcessor(self: PyOpenColorIO.Config, context: OpenColorIO_v2_0dev::Context, transform: PyOpenColorIO.Transform, direction: PyOpenColorIO.TransformDirection) -> OpenColorIO_v2_0dev::Processor`

`PyOpenColorIO.Config.GetProcessor(...) method of builtins.PyCapsule instance
    GetProcessor(*args, **kwargs)
    Overloaded function.
    
    1. GetProcessor(srcConfig: PyOpenColorIO.Config, srcColorSpaceName: str, dstConfig: PyOpenColorIO.Config, dstColorSpaceName: str) -> OpenColorIO_v2_0dev::Processor
    
    2. GetProcessor(srcContext: OpenColorIO_v2_0dev::Context, srcConfig: PyOpenColorIO.Config, srcColorSpaceName: str, dstContext: OpenColorIO_v2_0dev::Context, dstConfig: PyOpenColorIO.Config, dstColorSpaceName: str) -> OpenColorIO_v2_0dev::Processor
    
    3. GetProcessor(srcConfig: PyOpenColorIO.Config, srcColorSpaceName: str, srcInterchangeName: str, dstConfig: PyOpenColorIO.Config, dstColorSpaceName: str, dstInterchangeName: str) -> OpenColorIO_v2_0dev::Processor
    
    4. GetProcessor(srcContext: OpenColorIO_v2_0dev::Context, srcConfig: PyOpenColorIO.Config, srcColorSpaceName: str, srcInterchangeName: str, dstContext: OpenColorIO_v2_0dev::Context, dstConfig: PyOpenColorIO.Config, dstColorSpaceName: str, dstInterchangeName: str) -> OpenColorIO_v2_0dev::Processor`

**Comment by hodoulp** [comment]
For my understanding I did some experiments with `config` being an instance of the class `Config`:
```
>>> ocio.Config.GetProcessor(config, 'raw', config2, 'raw')
<PyOpenColorIO.Processor object at 0x10eee8960>
>>> config.GetProcessor(config, 'raw', config2, 'raw')
<PyOpenColorIO.Processor object at 0x10f80a730>
```
The second call succeeds as the method signature exists.

But the other way around fails:
```
>>> config.getProcessor('raw', 'raw')
<PyOpenColorIO.Processor object at 0x10eee8960>
>>> config.GetProcessor('raw', 'raw')
Traceback (most recent call last):
...
```
The second call fails because the method signature does not exist for `GetProcessor()`. The validation on the signature is risky on long-term e.g. adding a two-strings signature to the static method would lead to different behaviors on Python. 


So, the Python API is clearly ambiguous. I second the proposal to change the name of the static methods to `GetProcessorFromConfigs` so, it better clarifies the static method purpose.

**Comment by doug-walker** [comment]
@zachlewis , so does changing the GetProcessor function to GetProcessorFromConfigs address your concern?

If so, we will change both the C++ and Python API accordingly.  (The getProcessor methods will not be changed.)

**Comment by zachlewis** [comment]
That would be perfect. Thanks so much guys -- sorry for the confusion before.
