### ISSUE TITLE
C++/Python API Documentation Generation

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1148]
This issue is intended to host a discussion around the right approach for generating C++ and Python API docs for OCIO. @scoopxyz has done an excellent job investigating and starting to implement a method for automatic doc generation with `doxygen`, `breathe`, and a tool that ships with `pybind11`, but we have not yet decided if this is the approach to commit to.

The primary concern that's been raised in recent discussion is around complexity, both in terms of docstring formatting in OCIO headers, as well as Python-specific explanations in the Python bindings. OCIO v1 API doc generation was fairly simple, and leveraged some custom tooling (and Python stubs) to shoehorn both languages into Sphinx. The new approach adds complexity to this in hopes of unifying documentation between C++ and Python as much as possible, as well as leveraging tools that are readily available. I'll let @scoopxyz explain the current approach since he's the most knowledgeable.

We need to decide whether to:
1. Stick with the current approach and focus on completing it. As long as it's well documented, complexity can be managed.
2. Separate the C++ and Python docs. Embed Python docstrings in the pybind11 bindings (since the interface differs in various ways), and simplify the C++ docstring extraction. The idea here is that the Python docs are probably more critical for many OCIO users, since they are generally used by config authors, and C++ engineers may prefer using the headers as documentation (I do personally).
3. Do something else. Open to ideas, but hopefully suggestions leverage work that has already been done to some extent. The API is large, so the solution needs to scale well.

Whichever approach, I have some rare free cycles coming up (in one week) where I could probably complete this work. Let's discuss and come up with a resolution before the next Documentation working group meeting (09/25/2020) if possible. Thanks!

**Comment by michdolan** [comment]
#1074 features the current state of this work, for reference.

**Comment by scoopxyz** [comment]
This was the intended workflow here:

![Untitled Diagram](https://user-images.githubusercontent.com/22137450/93799048-818a9d00-fc36-11ea-805d-7e04dd55fe98.png)

General Overview:

1. Contributor writes docstrings for both C++ and Python simultaneously by adding Doxygen-formatted comments to the Public OCIO Headers
2. For **new** methods, the contributor runs the "docstrings" target which produces an additional "PyDocStr.h" header with string-literals for each method/class
3. The contributor must manually associate the string-literal with the appropriate method in the Python bindings (this would be done when they manually write the binding code
4. Contributor then runs the "docs" target which will extract the heads and auto-add them to the auto-doc class call for both C++ and Python docs in sphinx
5. Contributor would add additional .rst notes if the method deserves use cases or more elaborate discussion
6. Contributor commits code

This was the aim. At the time of writing the only thing preventing this is **ReadTheDocs**, which has no method of accessing the compiled Python library resulting in auto-doc failing. The workflow works today on a local machine.

Because ReadTheDocs can't compile Python libraries its self (time limitations), we would (like other libraries) have to make an elaborate hack to auto-generate skeleton python code with the docstrings included.

**Note:**
- This method does need a good amount of manual work for new methods (no way around this since they have to write python bindings anyway)
- The "mkdocs.py" python tool relies on Python Clang
- Docs strings will be word-for-word the same between the C++ and Python docs
- Contributor can always override the Python docstrings within the PyBind11 bindings themselves (an external header file could be used for organization)

**Comment by michdolan** [comment]
Thanks for the detailed explanation @scoopxyz !

**Comment by michdolan** [comment]
I've got `pybind11_mkdoc` hooked up in CMake to generate a docstring header, which could then use @scoopxyz 's updated Python bindings. My honest opinion after digging through all of this is that the cost to benefit ratio of `pybind11_mkdoc` is not worth it for our project. It's now it's own GH project, but is not versioned (i.e. no releases) and not in PyPi, so I don't feel 100% comfortable building a solution around it. It also introduces a dependency on Clang (and clang's Python bindings), and essentially gives us output equivalent to doxygen's output, but formatted differently.

I think we could write a Python tool to parse docstrings from doxygen XML and either:
1. Build a header identical to `pybind11_mkdoc` to allow embedding the docstrings into the bindings to support conventions like `help(<object>)` in Python. This would be fairly simple at first glance.
2. Inject docstrings into the Python bindings via a custom Sphinx plugin right before autodoc uses them. The downside to this approach is that the docstrings would not be persistent in the bindings to support inspection, etc. The benefit would be not requiring adding a doc argument to each part of the Python bindings source, but that's a small cost since @scoopxyz has already done most of that in #1074.

Opinions?

**Comment by michdolan** [comment]
After investigation and some tests, I can fairly easily generate a header file equivalent to `pybind11_mkdoc` just with the doxygen XML output. The trickier part is handling the description elements in the XML since there is quite a scope of functionality that it represents. I'm going to try and leverage `breathe` to parse the XML and to render RST for the header. In looking at the source I _think_ this would be a nice solution since it would leverage a single stack for doc generation.  This will take some time, but I'll start chipping away at it.
