### ISSUE TITLE
Add support for custom ComputeHash function/callback

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1150]
The current `ComputeHash` function in `PathUtils.cpp` depends on stat info from a supported filesystem. There could however be cases where this data is not sufficient for invalidating a cache (the filesystem might just be a proxy for a VCS system, for example), or a DCC could embed a file and use that when a config is not present. In these alternative cases, a function could be passed to OCIO to override the builtin hashing mechanism.

I would propose following a similar pattern as used in the current global `SetLoggingFunction` in the public API:

```
/// Define the logging function signature.
using LoggingFunction = std::function<void(const char*)>;
...
extern OCIOEXPORT void SetLoggingFunction(LoggingFunction logFunction);
```

Like:

```
using ComputeHashFunction = std::function<void(const std::string &)>;
...
SetComputeHashFunction(LoggingFunction logFunction);
```

**Comment by hodoulp** [comment]
Small improvement concerning the proposed method prototype:
```
using ComputeHashFunction = std::function<std::string(const std::string &)>;
SetComputeHashFunction(ComputeHashFunction hashFunction);
```

The method receives a file path (as a std::string) and returns a key (as a std::string) which uniquely identifies the file.

**Comment by zachlewis** [comment]
Just want to make sure I'm understanding correctly.

This proposal would provide a default method for computing a cache (e.g., with a file path std::string), while exposing a means to optionally override said method with a custom method. 

Who is the intended author of the custom hash-computation method? DCC application vendors and software developers, or for color pipeline developers and end-users, or either, or neither? Would / should this mechanism be promoted to the Python API?

In our pipeline, our FileTransforms usually find symlinks that point to the latest version of a certain transform, and the caching-related problem we experience most often is when a DCC application fails to 'realize' when a symlink points to something new. For instance, a Nuke user might 'publish' a new grade for a shot; and everyone working on that shot has to restart their Nuke session in order to see the updated grade.

I'm assuming what's happening is, the current cache-invalidating mechanism isn't aware of the original unresolved symlink, and is forever looking at the data that lives at the path resolved when the Processor was first created. If this is indeed what's happening, then it's not clear to me that a custom ComputeHash function would ever have the opportunity to re-resolve the original symlink either; i.e., if the resolved path itself is cached externally. 

There's a question in there somewhere. Am I barking up the right tree, or should I take my symlink woes elsewhere?

**Comment by EmperorYP7** [comment]
I've implemented custom callback along with `g_hashFunction` which stores current `ComputeHash()` by default which can be modified using `SetComputeHashFunction()`. Tests seem to be happy as well.
May I draft a PR for the same?

**Comment by hodoulp** [comment]
Hi @EmperorYP7 
That's an Open Source project so any contributors and contributions are welcome. Please create the pull request if you think to have an implementation for the feature, but do not forget to include at least one unit test to demonstrate that 'it works'.
Welcome on board

**Comment by EmperorYP7** [comment]
That sounds great to me @hodoulp :smile: Thanks!
