### ISSUE TITLE
Lut1DOpData::getCacheID bottleneck

### ISSUE THREAD

**Issue by MrKepzie** [AcademySoftwareFoundation/OpenColorIO#1198]
Hi,
We currently use OpenColorIO v2 in a compositing application. When profiling in release mode, most of our processing time is actually spent by OCIO trying to build its cache ID in Lut1DOpData::getCacheID using MD5. We already mainain a processor cache externally using our own parameters with the upside that it doesn't require to hash the whole LUTs.

I think the cache ID generation should be made optional in https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/9362128bb289984c0d8a824bede5407336846e9f/src/OpenColorIO/GPUProcessor.cpp#L117-L125
. While briefly looking over the code, I couldn't see any place this cache ID is "mandatory" for the library to work properly.

![Screenshot 2020-11-07 at 15 47 20](https://user-images.githubusercontent.com/4058448/98444187-abc5ea80-2110-11eb-8812-7c88da3a6d56.png)

Edit: caching the resulting GPUShaderDesc seems to resolve the issue.

**Comment by hodoulp** [comment]
@MrKepzie thanks for reporting the concern.

The cacheID is used to uniquely identify a color transformation so that's an important feature to build caches for example. But it costs a lot for some specific Ops such as luts because the content is part of the computation. For now, OpenColorIO has caches for `Processor`, `CPUProcessor`, and `GPUProcessor` instances.  On the other hand, the computation of the color transformation should only be done once (applicable to CPU and GPU code paths). When using the GPU code path, the `GPUShaderDesc` is the instance to keep in memory and to reuse anytime the same processing is needed. When using the CPU code path, the `CPUProcessor` is the instance to keep in memory.

As we are still actively working on the master branch with important changes, I would recommend you to always take the latest commit because we recently changed a lot the implementation around `GPUProcessor` to enter the processor caches, and fixed few bottlenecks. For example, PR #1130 adds processor caches but also removes a use of Lut1DOPData::getCacheID() for the resource name computation. When looking at the stack you pasted in the issue,  it seems that the latest commit should help.

The OCIOv2 is currently in stabilization period and not yet officially release so that's the perfect time to perform integration tests (and report issues or concerns) but a little bit early to use it in an official release.

**Comment by MrKepzie** [comment]
Ended up doing what you suggest. We frequently check against the master branch. Will look at that new caching feature.  Move to V2 was mandatory for the correct GPU compute code path. 
We have a specific usage for which I could open a feature request. Currently the shader text returned by the GPUShaderDesc contains uniforms declaration and helper functions. 
We however use that generated shader in a more complex GPU shader generation framework. The OCIO code-path ends up being just a piece of the final shader. We currently do string manipulation on the returned shader to extract manually from it the extra functions and uniform declarations, but this is bound to explode if the generated code changes frequently. (it broke only once over the past 6 to 12 months). 
For a use case such as ours, it would be beneficial to retrieve a _richer_ shader descriptor that we can translate to our own machinery more easily.

**Comment by hodoulp** [comment]
That's the goal of `GpuShaderCreator` to offer the ability for a completely custom integration i.e. the caller receives the requests but has to perform all the translation to its own environment. The class `GpuShaderDesc` provides much more support to ease traditional integrations.

**Comment by MrKepzie** [comment]
Perfect! Will give it a try when we get a chance

**Comment by hodoulp** [comment]
Hi @MrKepzie, In case you missed it, there is now an official OCIOv2 version available i.e. 2.0.0.

**Comment by MrKepzie** [comment]
Hey thanks for the bump, we picked it up actually

**Comment by hodoulp** [comment]
No more slowdown?

**Comment by MrKepzie** [comment]
works like a charm, did not have any issue so far

**Comment by hodoulp** [comment]
Can I close the issue?

**Comment by MrKepzie** [comment]
Yep
