### ISSUE TITLE
New warnings with gcc 10

### ISSUE THREAD

**Issue by hodoulp** [AcademySoftwareFoundation/OpenColorIO#1213]
When compiling the library with gcc 10, there are new warnings that we should cleanup at some point.

Thanks to Sandi Vujaković for the report.

[OpenColorIO GCC 10 warnings.txt](https://github.com/AcademySoftwareFoundation/OpenColorIO/files/5562298/OpenColorIO.GCC.10.warnings.txt)

**Comment by elsandosgrande** [comment]
@hodoulp Actually, they may not be all that new, just undetected until now. I always set `-Wall -Wextra`, and `-Wextra` was what led to these warnings showing up. Here, I rebuilt OpenTimelineIO with just `-g -Wextra` (I finally figured out how to manipulate CMake's variables from the command line, so there is no unwanted `-DNDEBUG` this time around :sweat_smile:) and got all of the same warnings: 
[OpenColorIO GCC 10 warnings no LTO&co.txt](https://github.com/AcademySoftwareFoundation/OpenColorIO/files/5566458/OpenColorIO.GCC.10.warnings.no.LTO.co.txt)


1. This thankfully shows that my custom compiler flags were not at fault (_phew_).
2. Since you said in the Slack workspace that even simple warnings must be investigated and fixed, I'm going to assume that this is a valid ticket in spite of the warnings being triggered by additional warning flags.

**Comment by hodoulp** [comment]
@elsandosgrande If I understand the `-Wextra` flag is missing. That's definitively a flag to add. You put such an energy on the investigation 👍 that you can do the pull request if you have time.

**Comment by elsandosgrande** [comment]
I haven't actually forked the repository, just cloned it locally :sweat_smile:. That, and I haven't actually tried to modify CMake configuration files before, as I only ever needed to kind of understand them from reading them, so I'm not the right guy to modify this. Thank you for the compliment though!

**Comment by hodoulp** [comment]
Closing the issue as all the warning should now be fixed!
