### ISSUE TITLE
API documentation: python reference to classes 

### ISSUE THREAD

**Issue by BernardLefebvre** [AcademySoftwareFoundation/OpenColorIO#1265]
In C++ headers, when comment names another API class the produced documentation does create a link to that class documentation.

For instance, LogCameraTransform does reffer to LogAffineTransform:
![LogCameraCpp](https://user-images.githubusercontent.com/37628108/104732400-2e6bb700-570b-11eb-8e71-7dcc76a017c6.png)

If the Python bindings uses the same comment, no link is created. It seems that the class name would need to follow 'PyOpenColorIO.':
![LogCameraPython](https://user-images.githubusercontent.com/37628108/104732726-a2a65a80-570b-11eb-902b-a5683f1730b7.png)

Is there a way to reuse the same documentation, or should we in that case maintain both the C++ and the Python documentation?

**Comment by michdolan** [comment]
The C++ docs are being built by breathe in this case, and the Python docs by the code I wrote to extract the same Doxygen source for use in the Python bindings. That's why there is some difference. We should be able get to a matching state, but will require some refinement to the process. Some of these differences may work themselves out as the header docs are made more consistent as well.
