### ISSUE TITLE
Differences between v1 GPU path and v2 Legacy GPU Path

### ISSUE THREAD

**Issue by est77** [AcademySoftwareFoundation/OpenColorIO#1294]
While trying to update an app using OCIO v1 to OCIO v2 I found some differences in the GPU path transforms between the 2 versions when applying the transforms to HDR images. CPU transforms match.

I am using OpenColorIO v2.0.0-rc1 with the ACES 1.0.3 config. Same config in both versions.

V1 CPU: 
![image](https://user-images.githubusercontent.com/409013/106118812-cda19d00-6154-11eb-8181-478ccccfd5ff.png)

V2 CPU:
![image](https://user-images.githubusercontent.com/409013/106118912-e8741180-6154-11eb-9892-07cb5ec634c9.png)

V1 GPU:
![image](https://user-images.githubusercontent.com/409013/106118976-f6c22d80-6154-11eb-90dc-e1f62e60f9f7.png)

V2 Legacy GPU:
![image](https://user-images.githubusercontent.com/409013/106119031-05104980-6155-11eb-930f-7841f3a9c569.png)

Thanks!

**Comment by est77** [comment]
I updated my app to use the final v2.0 release and I can confirm that the clamping is still present in the GPU legacy engine (the one that bakes all transforms into a single 3d LUT).

**Comment by chrisbrejon** [comment]
Yeah same thing here. We have the exact same behavior in our render view.
Thanks !

**Comment by remia** [comment]
I think the allocation / allocationvars are lost after optimization (even with optimization == none as they are no-op) so that when `extractGpuShaderInfo` try to query them in `PartitionGPUOps` to add the appropriate shaper in the shader nothing is left to see.

I can confirm that when using ociodisplay and trying to apply a ACES2065-1 to ODT - sRGB transform (ACES Config 1.2), the shader generated for gpulegacy doesn't have any log shaper and that's not correct.

**Comment by chrisbrejon** [comment]
Thanks Remi ! You rock !

**Comment by doug-walker** [comment]
Hi Remi, thanks.  Yes, Patrick and I are aware of the problem.  We have a PR in progress.

**Comment by est77** [comment]
Thanks for looking into it.
