### ISSUE TITLE
Add support for Imath repo Half library

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#1367]
The nightly Analysis "latest" CI jobs are failing do to OpenEXR GH restructuring. We'll need to change that dependency over to Imath where Half now lives (OpenEXR 3), and make sure OCIO supports both that and the OpenEXR 1-2 bundled Half lib.

**Comment by remia** [comment]
Not sure this is the correct issue nor what is the status of this but the following might be relevant.

Since `brew` decided to update my entire system, I got a new OIIO using OpenEXR@3 while still using the Half@2.4.0 for OCIO. This produced errors in finding OpenEXR header when importing OIIO headers from OCIO apps. The fix I used for this specific issue was to simply delete the `FindOpenImageIO.cmake`, it seems that even the lowest OIIO we support, 2.1.9, was shipping with CMake Config scripts. This Config script correctly set the headers path while the Find module didn't appear to so I didn't bother.

Maybe @lgritz can confirm that we don't need this Find module anymore.

**Comment by lgritz** [comment]
Since OIIO 2.1, OIIO has exported a good config file, so the FindOpenImageIO should no longer be needed. OIIO itself no longer distributes a Find module.

**Comment by hodoulp** [comment]
Another unfortunate result of updating the macOs is that the library name for the new `Imath` and the old `ilmbase` is the same causing issues. Refer to the [OSL thread](https://lists.aswf.io/g/osl-dev/topic/macos_makefile_generation/83140580?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,83140580) for details.
