### ISSUE TITLE
How to link freeglut instead GLUT?

### ISSUE THREAD

**Issue by Mederim** [AcademySoftwareFoundation/OpenColorIO#1576]
I use freeglut as dependencie and opencolorio cannot find.

```
-- The CXX compiler identification is GNU 11.2.0
-- The C compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting C++ version to '11' as none was specified.
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Found OpenGL: /usr/lib/libOpenGL.so  found components: OpenGL 
-- Found GLEW: /usr/local/include (found version "2.2.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'glut'
--   Package 'glut', required by 'virtual:world', not found
-- Could NOT find GLUT (missing: GLUT_glut_LIBRARY) 
-- Use "GLUT_ROOT" to specify an install location
CMake Warning at share/cmake/utils/CheckSupportGL.cmake:47 (message):
  GPU rendering disabled
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)
```
Tried to use -DGLUT_ROOT=/usr/include/GL/freeglut.h and not worked.

I currently have this paths in freeglut:

```
/usr/lib64/pkgconfig/freeglut-gles.pc
/usr/lib64/pkgconfig/
/usr/lib64/libfreeglut-gles.so.3.11.0
/usr/lib64/libfreeglut-gles.so.3
/usr/lib64/libfreeglut-gles.so
/usr/lib64/libfreeglut-gles.a
/usr/lib64/cmake/FreeGLUT/FreeGLUTTargets.cmake
/usr/lib64/cmake/FreeGLUT/FreeGLUTTargets-noconfig.cmake
/usr/lib64/cmake/FreeGLUT/FreeGLUTConfigVersion.cmake
/usr/lib64/cmake/FreeGLUT/FreeGLUTConfig.cmake
/usr/lib64/cmake/FreeGLUT/
/usr/lib64/cmake/
/usr/lib64/
/usr/include/GL/glut.h
/usr/include/GL/freeglut_ucall.h
/usr/include/GL/freeglut_std.h
/usr/include/GL/freeglut_ext.h
/usr/include/GL/freeglut.h
/usr/include/GL/
/usr/include/
/usr/
```

**Comment by Simran-B** [comment]
`-DGLUT_ROOT` needs to be a path prefix, not a full path to a header file (see [`<PackageName>_ROOT`](https://cmake.org/cmake/help/latest/envvar/PackageName_ROOT.html)).

Based on https://github.com/Kitware/CMake/blob/90c83564f0ea3fc9a9edd8cf141cf18955ccd900/Modules/FindGLUT.cmake#L174 I guess it should be `-DGLUT_ROOT=/usr/include` (or `/usr/include/GL` but that is a path that is already on the list of default locations). However, that code path isn't used because pkg-config is present on your machine.

The problem might be that pkg-config doesn't see freeglut as suitable to fulfill the GLUT dependency or there's something wrong with the installed package. How did you obtain freeglut? What's the content of the .pc file?

You could try to bypass pkg-config and see if that helps. Remove the cmake cache and use `-DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=TRUE`.

**Comment by Mederim** [comment]
Tried `-DGLUT_ROOT=/usr/include` and same error. My .pc of freeglut is `freeglut-gles.pc` and theres is the content:

```
prefix=/usr
libdir=/usr/lib64
Includedir=${prefix}/include
Name: glut
Description: A freely licensed and improved alternative to the GLUT library
Version: 3.2.1
Libs: -L${libdir} -lfreeglut-gles
Libs.private: -lwayland-client -lwayland-cursor -lwayland-egl -lGLESv2 -lG
LESv1_CM -lEGL -lxkbcommon -lm
Cflags: -I${includedir} -DFREEGLUT_GLES;-DFREEGLUT_STATIC
```
I builded freeglut with source code and made for pure wayland systems without X and used the follow flags:

```
-DFREEGLUT_WAYLAND=ON
-DFREEGLUT_GLES=ON
-DFREEGLUT_BUILD_DEMOS=OFF
```

Using `-DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=TRUE` break the build.

**Comment by hodoulp** [comment]
Note that `GLUT_ROOT` must point to a root directory when to find `include`, `lib` (or `lib64`), `share` and `bin` sub-directories.

**Comment by Mederim** [comment]
@hodoulp but GLUT_ROOT is pointed to `/usr/include` this is not a root dir?

**Comment by Simran-B** [comment]
Can you try `/usr`?

**Comment by Mederim** [comment]
@Simran-B Still same error:
```
-- The CXX compiler identification is GNU 11.2.0
-- The C compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting C++ version to '11' as none was specified.
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Found OpenGL: /usr/lib/libOpenGL.so  found components: OpenGL 
-- Found GLEW: /usr/local/include (found version "2.2.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'glut'
--   Package 'glut', required by 'virtual:world', not found
-- Could NOT find GLUT (missing: GLUT_glut_LIBRARY) 
-- Use "GLUT_ROOT" to specify an install location
CMake Warning at share/cmake/utils/CheckSupportGL.cmake:47 (message):
  GPU rendering disabled
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)
```

**Comment by dekekincaid** [comment]
I'm using GLUT_LIBRARIES & GLUT_INCLUDE_DIR

**Comment by Mederim** [comment]
@dekekincaid used: 

```
-DGLUT_ROOT=/usr 
-DGLUT_LIBRARIES=/usr/lib 
-DGLUT_INCLUDE_DIR=/usr/include/GL
```
And also:

```
-DGLUT_ROOT=/usr
-DGLUT_LIBRARIES=lib 
-DGLUT_INCLUDE_DIR=/usr/include
```

**Comment by dekekincaid** [comment]
GLUT_LIBRARIES needs to point to the actual .so/.a/.dylib file, not a dir.  GLUT_INCLUDE points to the dir.

**Comment by Mederim** [comment]
@dekekincaid like this?
```
-DGLUT_ROOT=/usr 
-DGLUT_INCLUDE_DIR=/usr/lib 
-DGLUT_LIBRARIES=/usr/lib/libfreeglut-gles.so
```

**Comment by dekekincaid** [comment]
More like:

-DGLUT_INCLUDE_DIR=/usr/include 
-DGLUT_LIBRARIES=/usr/lib/libfreeglut-gles.so

GLUT_ROOT doesn't work for me so I don't set it.

**Comment by Mederim** [comment]
@dekekincaid still the same error:
```
-- Checking for module 'glut'
--   Package 'glut', required by 'virtual:world', not found
-- Could NOT find GLUT (missing: GLUT_glut_LIBRARY) 
-- Use "GLUT_ROOT" to specify an install location
```

**Comment by Simran-B** [comment]
I tried to build OCIO in an Ubuntu 21.10 Docker container and it picked up GLUT just fine:

```
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components: OpenGL
-- Found GLEW: /usr/include (found version "2.1.0")
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so
```

The library is provided by the `freeglut3-dev` package as `dpkg -S libglut` confirms:

```
freeglut3-dev:amd64: /usr/lib/x86_64-linux-gnu/libglut.a
freeglut3:amd64: /usr/lib/x86_64-linux-gnu/libglut.so.3
freeglut3:amd64: /usr/lib/x86_64-linux-gnu/libglut.so.3.9.0
freeglut3-dev:amd64: /usr/lib/x86_64-linux-gnu/libglut.so
```

CMake does not report "Found PkgConfig" for me. `pkg-config --version` reports 0.29.2, which seems quite dated. I guess the `pkg-config` package is superseded by `pkgconf`, which has version 1.7.3. But even then, it doesn't appear to be used for GLUT discovery in my case. I checked CMake's `FindGLUT.cmake` module and it doesn't actually use pkg-config in version 3.18. In the latest CMake version 3.22.x, the module does try to use pkg-config and that fails for me as well with error `Package 'glut', required by 'virtual:world', not found.

As far as I can tell, the problem is that the freeglut3-dev package doesn't come with a `.pc` file under Ubuntu. If I compile and install FreeGLUT myself (had to install `libxi-dev` for `XInput.h`), then I do get one at `/usr/local/lib/x86_64-linux-gnu/pkgconfig/glut.pc` and it's picked up by CMake for the OCIO build. You don't seem to have this problem but on the other hand you use freeglut-gles which might be different.

Can you try the following commands?
```
pkg-config --modversion glut
pkg-config --modversion freeglut-gles
```

I expect the former to fail with the familiar error message and the latter to print `3.2.1`. A simple workaround could be to symlink the `freeglut-gles.pc` file so that pkg-config will also use this configuration if `glut` and not `freeglut-gles` is requested:

```
cd /usr/lib64/pkgconfig/
ln -s freeglut-gles.pc glut.pc
```

**Comment by Mederim** [comment]
@Simran-B yeah that worked.
```
-- Checking for module 'glut'
--   Found glut, version 3.2.1
-- Found GLUT: TRUE 
```

**Comment by Mederim** [comment]
I will make a patch to the package i tried to port so it will fixed. Its a good idea too add a option to detect freeglut-gles instead.

**Comment by Simran-B** [comment]
You could also submit a patch upstream to pick up either glut or freeglut-gles: https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindGLUT.cmake#L96

**Comment by Simran-B** [comment]
`-DGLUT_glut_LIBRARY=/usr/lib64/libfreeglut-gles.so` might work too but bypasses the CMake check. It will report that it found GLUT even if this internal variable is set to a non-existing path.

I created an issue upstream: https://gitlab.kitware.com/cmake/cmake/-/issues/23077
