### ISSUE TITLE
v2.1.1 fails to build from source on Debian unstable/sid due to rst custom rules in documentation

### ISSUE THREAD

**Issue by mfvescovi** [AcademySoftwareFoundation/OpenColorIO#1583]
Hi!

While test-building OpenColorIO v2.1.1 to update obsolete version in Debian archives, something in the documentation rst rules is wrong, as it fails as follows:

= = = = >8 = = = =
CMake Error at docs/CMakeLists.txt:107 (add_custom_command):
  Attempt to add a custom rule to output

    /<<PKGBUILDDIR>>/debian/cmake/docs/pyopencolorio_allocation.rst.rule

  which already has a custom rule.
= = = = >8 = = = =

This same error message is shown for every rst file in the documentation dir tree.
On the contrary, if CMake option for documentation generation to OFF at build time, the process succeeds.

The full `[buildlog](https://github.com/AcademySoftwareFoundation/OpenColorIO/files/7834152/opencolorio_2.1.1%2Bdfsg-1_buildlog.txt)` is attached.

Feel free to ping me for more info.

**Comment by remia** [comment]
Thanks for the report @mfvescovi.

I didn't reproduce the error on macOS but it seems your build process is slightly more complex than what I'm used to. From the log I'm not exactly clear, are you calling CMake configure twice (from /<< PKGBUILDDIR>> and /<< PKGBUILDDIR>>/debian/cmake)? Not that it should break things but trying to understand what's going on.

Was that problem here in 2.1.0 and previous release?
