### ISSUE TITLE
Choice of hash function for caching

### ISSUE THREAD

**Issue by remia** [AcademySoftwareFoundation/OpenColorIO#1645]
Starting from v2, we use hashing more heavily in the library, notably to compute the various Processor `cacheID`. The current algorithm we use is based on MD5 which is probably not the best fit for our use case. As pointed out in a recent slack discussion, we should use a non cryptographic hash with reasonable speed and good quality (minimise collisions). Some candidates were mentioned: [farmhash](https://github.com/google/farmhash), [xxhash](https://github.com/Cyan4973/xxHash) or [wyhash](https://github.com/wangyi-fudan/wyhash). Some comparisons are also available from this [article](https://aras-p.info/blog/2016/08/09/More-Hash-Function-Tests/) (from 2016).

As an example, see this [PR](https://github.com/remia/OpenColorIO/pull/36) which replace MD5 by `xxHash`. This gives good speedup, around 10-15x for a 65 3DLUT cacheID (6ms to 0.4ms). This is imported as a header only library, similar to how we use `sampleicc`. If there is reluctance to add such a (internal) dependency, we could also choose to use something simpler by default in the library and provide user override like we already do for the filename hash function. From C++ 17, `std::hash` has a specialisation for `string_view` which could fit our needs but it wouldn't be available for all our supported environments so probably gets disqualified.

As an example where the current implementation can be relatively slow, consider an application generating a `Processor` representing a full colour management pipeline. Depending on the source, this could mean inverting the colour rendering, applying a number of looks, then colour rendering again. Such a `Processor` can contain a number of 1D and 3DLUT. While the `Processor` outer cache uses a simplified hash not including the LUT entries, the fallback mechanism does. In my example case, where per shot context changes, this adds at minimum around 24ms to the `Processor` creation time just for the fallback. This is also valable if the client code call the `Processor::getCacheID()`.

Example `ocioperf` number on a heavy Processor:
```
Create the (display, view) processor:   For 50 iterations, it took: [2000.68, 27.5805, 67.0426] ms
// Switch to xxHash
Create the (display, view) processor:   For 50 iterations, it took: [2182.96, 4.08732, 47.6649] ms
```

Any thoughts?

**Comment by zachlewis** [comment]
My only thoughts are, that's pretty damn cool, Remi. 
Presumably, transform hashes would be constant across architectures and platforms, right?

**Comment by remia** [comment]
> My only thoughts are, that's pretty damn cool, Remi. Presumably, transform hashes would be constant across architectures and platforms, right?

At least from what I see in xxHash first lines of ReadMe yes, but that's probably something to check for the others options as well. Do you have already a use case for that @zachlewis ?

> Code is highly portable, and hashes are identical across all platforms (little / big endian).

**Comment by zachlewis** [comment]
> At least from what I see in xxHash first lines of ReadMe yes, but that's probably something to check for the others options as well. Do you have already a use case for that @zachlewis ?

Nothing I've implemented in earnest yet, and I've been meaning to verify that the current hashing mechanism is stable across platforms / architectures; but I've been experimenting with using the cacheID of the most losslessly-optimized version of a given transform (or transforms) as the ProcessList "id" (i.e., CLF and CTF metadata). 
(And I'm not sure this is the wisest decision to begin with, because even though they amount to the same thing computationally, I dunno if the "id" should refer to the cumulative transform, or the unique composition thereof and likewise, I think I'd rather have two IDs for my purposes -- one identifying the "purest", highest-resolution version of a given transform -- parametric transforms, half-domain LUT1Ds, finishing-tier cubes -- and one for identifying the "current", comparatively lossy version of the transform as it exists in a given serialized form and container ).

Basically, I was considering using hashes as a means for uniquely identifying transforms (i.e., via a lookup table -- which may as well be an OCIO config utilizing Named Transforms), independent of any other information (CLF/CTF metadata, OCIO color space naming, ACEStransformIDs, file naming, whatever). Could also be used for identifying identical transforms across (and within) separate configs, sort of like ad-hoc "equality groups" -- which I'd imagine would be useful for cross-config communication. I was considering opening a ticket suggesting such a capability (that cross-config Processors obey equality group equivalence as a means for interfacing with each other, as an alternative to specifying interchange roles; but I also like the idea of mandatory interchange roles.)

This would be particularly useful in pipelines such as ours, where we use FileTransforms to reference filenames that reflect a general task ("camera_decoding.ctf") rather than a specific transform ("Log3G10_RWG_to_ACES.ctf"). (In practice, the less specific file/names are actually symlinks to more specific file/names, but I'm trying to come up with a way of representing that same context-bound variance without relying on the filesystem -- i.e., for use with config archives)


Additionally, Autodesk's SynColor schema seems to have `Info/Functional_MD5` element, which, presumably, is used for similar purposes -- unique identification of a transform (or optimized form of a transform?). I guess Doug could probably speak to that.


ANYWAY -- I wouldn't personally be heartbroken if whatever hash scheme we choose varies across platforms and architectures, for the sake of speed -- although I do think it would be useful if the API provided an easy way to compute a architecture-platform-invariant hash that _can_ be used for such purposes as identification, even if it's not the same hash scheme used internally for cache IDs).


(sidebar -- you wouldn't believe just how much storage multiple versions of the same LUTs with different file names can take up at a finishing facility! I can recall one facility that at one point had decided to just name all their LUTs after MD5 hashes; and apparently, they pretty quickly decided to stop doing that, and to go back to human readable filenames)

**Comment by remia** [comment]
Thanks for the answer @zachlewis.

> and I've been meaning to verify that the current hashing mechanism is stable across platforms / architectures

It seems to be the case as it is checked in the unit tests in a few places:
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/tests/cpu/Processor_tests.cpp#L31
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/tests/cpu/GpuShader_tests.cpp#L40
https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/tests/cpu/CPUProcessor_tests.cpp#L820

> I was considering opening a ticket suggesting such a capability (that cross-config Processors obey equality group equivalence as a means for interfacing with each other, as an alternative to specifying interchange roles; but I also like the idea of mandatory interchange roles.)

Interesting thought, although the interchanges roles have indeed other use cases as discussed elsewhere to bridge with other color management systems. I assume for this ad-hoc equality group detection, you would still need to have known anchor point in each configs to make sure the comparison of transform hash is meaningful.

Am I understanding correctly that the other things you mention mostly revolve around storage space savings?

In any case, I think we should maintain the existing behaviour, that is architecture / platform independent hash, which xxHash seem to already provide.
