### ISSUE TITLE
Install the pkg-config file when building under MSYS on windows?

### ISSUE THREAD

**Issue by agriggio** [AcademySoftwareFoundation/OpenColorIO#1680]
Hi,
it would be good if the pkg-config script (`OpenColorIO.pc`) was installed when building under MSYS on windows. Here's a simple patch to do that:

```diff
--- b/src/OpenColorIO/CMakeLists.txt	2022-06-05 20:59:43.000000000 +0200
+++ a/src/OpenColorIO/CMakeLists.txt	2022-08-23 17:17:20.516786583 +0200
@@ -171,7 +171,7 @@
     SystemMonitor.cpp
 )
 
-if(NOT WIN32)
+if(NOT WIN32 OR MSYS)
 
     # Install the pkg-config file.
 
```

**Comment by kmilos** [comment]
This should be `MINGW` instead of `MSYS`. (`MSYS` is a POSIX emulation environment like Cygwin where I doubt OCIO is useful; one is typically building for the WIn32 API, i.e. MINGW).

`pkg-config` runs everywhere (available via [vcpkg ](https://vcpkg.io/en/docs/maintainers/ports/vcpkg-pkgconfig-get-modules.html)for MSVC), so the `if` clause should just be simply removed and the pc filed installed always.

**Comment by amyspark** [comment]
[pkgconf](https://github.com/pkgconf/pkgconf) is also a working alternative if you use Meson.

**Comment by kmilos** [comment]
Indeed, vcpkg seem to use meson+pkgconf quite a bit for Win32 packaging.

**Comment by doug-walker** [comment]
@agriggio , @kmilos , @amyspark  Please review PR #1720 and check that it meets your needs, thanks!
