### ISSUE TITLE
GetProcessorFromBuiltinColorSpace with "noop" transform does not result in isNoOp() returning true

### ISSUE THREAD

**Issue by SRHMorris** [AcademySoftwareFoundation/OpenColorIO#1830]
Tested using the `ocio://default` config, using OCIO v2.2.1

``` c++
auto config = OCIO::Config::CreateFromFile("ocio://default");
auto proc = OCIO::Config::GetProcessorFromBuiltinColorSpace("ACEScg", config, "ACEScg");
bool noop = proc->isNoOp();
assert(noop);
```

When generating the shader text it is quite clearly a noop.

For my use case I kind of want to rely on this specific case returning a noop processor (more specifically when using the `OCIO::ROLE_SCENE_LINEAR` role) as an optimization.

**Comment by doug-walker** [comment]
@SRHMorris , that's because the Processor has not been optimized, it is just the concatenation of the to-reference and from-reference transforms.  If you were processing pixels, you would generate a CPUProcessor or GPUProcessor from the Processor and that would optimize it.  But if you just want to run the optimizer without processing pixels, you may use the getOptimizedProcessor method.  Calling isNoOp on the result of that would be a no-op, in your case.

**Comment by SRHMorris** [comment]
@doug-walker thanks for your help, that does seem work so I'll close this issue.
