### ISSUE TITLE
Access older docs from website

### ISSUE THREAD

**Issue by scoopxyz** [AcademySoftwareFoundation/OpenColorIO#512]
No convenient way to see previous release documentation from webpage

**Comment by rashil2000** [comment]
Hey, any updates on this issue?
This seems to be a good starting point for contribution.

**Comment by hodoulp** [comment]
@michdolan @scoopxyz Any hints?

**Comment by michdolan** [comment]
This is potentially a major undertaking. Currently the OCIO webpage is static, fed from the ``gh-pages`` branch of this repo. Ideally we would be able to do something like what RTD supports, where you can browse docs from each past release, as well as from the current development branch (``master`` in our case). A good illustration of this is the landing page of OpenImageIO's docs: https://readthedocs.org/projects/openimageio/

I believe that was the overall spirit of this issue.  Correct me if I'm wrong @scoopxyz

**Comment by rashil2000** [comment]
Cool! I can get started with integrating RTD in this repo.
It'll be great if you can provide some resources to get started along.

**Comment by michdolan** [comment]
Thanks for your interest in contributing @rashil2000 . Before you start on anything, let's get input from @scoopxyz , who was doing some initial work on this already. There were mixed opinions about the right way to approach it, and there mmight need to be some community discussion first. If you are in the OCIO Slack, that's a good place to field the question too, since it has been discussed there a few times. IF you're not in Slack, let me know and I can invite you.

**Comment by rashil2000** [comment]
I'm not on the Slack workspace. Please send me an invite at rashil2000@gmail.com.

**Comment by michdolan** [comment]
We discussed this in the TSC meeting today. Since @rashil2000 was able to stand up RTD so quickly, but is blocked by the need to build OCIO to get complete docs (due to CMake target dependencies), that raises the point that the doc build system itself could be revisited.

Being able to build the docs via CMake is important, but if the Sphinx build process could be decoupled from CMake, and run independently (with only Python),  RTD could then use that independent of CMake. An initial investigation could involve trying to extract the C++ and Python  doc build logic from CMake (this should be possible without having to rewrite the doc extraction code itself, since both utilities are already written in Python), and wrap it in a Python or bash script so that the entire OCIO docs can be built in isolation with only the existing rtd files, C++ headers, and Python stubs.

@rashil2000 if you have interest in continuing your work here, we can continue to support you as needed. Thanks for your work so far!
