### ISSUE TITLE
Update CI builds to use DockerHub image

### ISSUE THREAD

**Issue by michdolan** [AcademySoftwareFoundation/OpenColorIO#604]
Building the docs in CI builds is creating a lot of false failures, only due to problems with apt-get installing tex, which is used to create PDF docs. 

Generating PDF docs is not a critical need for CI builds. HTML docs on the other hand, which have no tex dependency, are beneficial in that they validate documentation *can* be built.

If we create an additional "html" target to go with the "pdf" and overall "docs" targets, CI builds could just test the HTML build.

**Comment by michdolan** [comment]
Related to PR #603

**Comment by scoopxyz** [comment]
Reminding myself to comment. I don't think its worthwhile to fracture the targets just for doc types. The real issue is the CI machine setup times. What the real fix should be is using DockerHub to directly pull our dev images into our CI infrastructure, so any dev off the street can directly jump into a compatible dev world and our CI setup times would be roughly constant.

**Comment by michdolan** [comment]
Good point. I agree that would be a better solution. I can edit this issue to that end.

**Comment by michdolan** [comment]
CI is now using DockerHub images on Linux, provided by the aswf-docker project,
