### ISSUE TITLE
Add option to skip OCIO_ACTIVE_DISPLAYS / OCIO_ACTIVE_VIEWS

### ISSUE THREAD

**Issue by jeremyselan** [AcademySoftwareFoundation/OpenColorIO#66]
Currently, if OCIO_ACTIVE_DISPLAYS / OCIO_ACTIVE_VIEWS envvars are defined, there is no way to defeat their use.  What if the user wanted to display a list of displays or views that is never filtered? (Such as for a command-line tool). Perhaps the API calls to query should take an extra arg skipfilter (which defaults to false).

**Comment by KelSolaar** [comment]
Hi,

Doing some necromancy on this one, as discussed on Slack I got bitten hard by `OCIO_ACTIVE_DISPLAYS` being set in the shells I was launching my IDE from to update a config. The result was that instead of having my 4 or 5 expected displays I was getting only the one defined in `OCIO_ACTIVE_DISPLAYS` when building the config. Took me really long time to understand what was going on.

Talked with @doug-walker that it would be a good idea to provide a mechanism to entirely  ignore them when you are programmatically creating a config.

Cheers,

Thomas

**Comment by doug-walker** [comment]
Closing this as fixed, @KelSolaar.  In v2 we have API calls getNumDisplaysAll and getNumViews(type, display) that may be use to ignore the active display and view lists.
